//This file was generated by script mkregs.py

#include "iob_timer_swreg.h"


// Base Address
static int base;
void IOB_TIMER_INIT_BASEADDR(uint32_t addr) {
	base = addr;
}

// Core Setters
void IOB_TIMER_SET_RESET(uint8_t value) {
	(*( (volatile uint8_t *) ( (base) + (TIMER_RESET) ) ) = (value));
}

void IOB_TIMER_SET_ENABLE(uint8_t value) {
	(*( (volatile uint8_t *) ( (base) + (TIMER_ENABLE) ) ) = (value));
}

void IOB_TIMER_SET_SAMPLE(uint8_t value) {
	(*( (volatile uint8_t *) ( (base) + (TIMER_SAMPLE) ) ) = (value));
}


// Core Getters
uint32_t IOB_TIMER_GET_DATA_HIGH() {
	return (*( (volatile uint32_t *) ( (base) + (TIMER_DATA_HIGH) ) ));
}

uint32_t IOB_TIMER_GET_DATA_LOW() {
	return (*( (volatile uint32_t *) ( (base) + (TIMER_DATA_LOW) ) ));
}

