//This file was generated by script mkregs.py

#include "iob_uart_swreg.h"


// Base Address
static int base;
void IOB_UART_INIT_BASEADDR(uint32_t addr) {
	base = addr;
}

// Core Setters
void IOB_UART_SET_SOFTRESET(uint8_t value) {
	(*( (volatile uint8_t *) ( (base) + (UART_SOFTRESET) ) ) = (value));
}

void IOB_UART_SET_DIV(uint16_t value) {
	(*( (volatile uint16_t *) ( (base) + (UART_DIV) ) ) = (value));
}

void IOB_UART_SET_TXDATA(uint8_t value) {
	(*( (volatile uint8_t *) ( (base) + (UART_TXDATA) ) ) = (value));
}

void IOB_UART_SET_TXEN(uint8_t value) {
	(*( (volatile uint8_t *) ( (base) + (UART_TXEN) ) ) = (value));
}

void IOB_UART_SET_RXEN(uint8_t value) {
	(*( (volatile uint8_t *) ( (base) + (UART_RXEN) ) ) = (value));
}


// Core Getters
uint8_t IOB_UART_GET_TXREADY() {
	return (*( (volatile uint8_t *) ( (base) + (UART_TXREADY) ) ));
}

uint8_t IOB_UART_GET_RXDATA() {
	return (*( (volatile uint8_t *) ( (base) + (UART_RXDATA) ) ));
}

uint8_t IOB_UART_GET_RXREADY() {
	return (*( (volatile uint8_t *) ( (base) + (UART_RXREADY) ) ));
}

